# Generated by Django 6.0.1 on 2026-01-31 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cidr', models.CharField(max_length=18)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('is_active', models.BooleanField(default=True)),
                ('excluded_ips', models.TextField(blank=True, help_text='Comma-separated IPv4 addresses to exclude')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddressAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('status', models.CharField(choices=[('USED', 'Used'), ('RELEASED', 'Released')], default='USED', max_length=10)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_allocations', to=settings.AUTH_USER_MODEL)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ipmanager.subnet')),
            ],
            options={
                'indexes': [models.Index(fields=['subnet', 'status'], name='ipmanager_i_subnet__43cd48_idx'), models.Index(fields=['owner', 'status'], name='ipmanager_i_owner_i_441ddc_idx')],
                'constraints': [models.UniqueConstraint(fields=('subnet', 'ip'), name='uniq_ip_per_subnet')],
            },
        ),
    ]
