# Generated by Django 6.0.1 on 2026-01-31 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanager', '0003_ipaddressallocation_released_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressallocation',
            name='claimed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
